spring.application.name=SmartBalance
spring.datasource.url= jdbc:postgresql://localhost:5432/smart-balance
spring.datasource.username= postgres
spring.datasource.password=senha

spring.jpa.show.sql= true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update